export const STATUS_TRANSITIONS = {
  NOT_SUBMITTED:  ["SUBMITTED", "WITHDRAWN"],
  SUBMITTED:      ["INTERVIEWING", "REJECTED", "WITHDRAWN"],
  INTERVIEWING:   ["OFFER_RECEIVED", "REJECTED", "WITHDRAWN"],
  OFFER_RECEIVED: ["OFFER_ACCEPTED", "OFFER_DECLINED", "WITHDRAWN"],
  OFFER_ACCEPTED: ["NOT_SUBMITTED"],
  OFFER_DECLINED: ["NOT_SUBMITTED"],
  REJECTED:       ["NOT_SUBMITTED"],
  WITHDRAWN:      ["NOT_SUBMITTED"],
};
